### PR TITLE
Interior Lighting

### PR DESCRIPTION
**Pull request by MagnetAss**
Added interior lighting for rotary wing and IFV

### CODE REVIEW

**Comment by SpanishSurfer** [comment]
Ready for merge?

**Comment by MagnetAss** [comment]
Indeed! :D

**Comment by SpanishSurfer** [comment]
Tested? No bugs?  No script errors?

**Comment by MagnetAss** [comment]
Yeah, I was able to run the server as normal. No conflicts or strange errors, although I wouldn't mind getting rid of the initialization message.

**Comment by SpanishSurfer** [comment]
That should be easy, if you know what it says search for the text and delete. Let me know if it works and I'll merge.

**Comment by MagnetAss** [comment]
Nothing that I saw, no errors or conflicts, Ran the server and tested
various vehicles.

**Comment by MagnetAss** [comment]
The fact that I was using the mission from 12 days ago won't matter, will
it?

**Comment by SpanishSurfer** [comment]
Yes, mission has changed since...You can pull my changes into your fork by using this guy's instructions:  https://www.youtube.com/watch?v=-zvHQXnBO6c&list=PLz1dFjnEAe7IJ9frqTC2lhVSoqocb-8CQ&index=6

**Comment by MagnetAss** [comment]
It's the last 3 lines

**Comment by MagnetAss** [comment]
I'll synch it up real fast

**Comment by MagnetAss** [comment]
testing removal of message

**Comment by MagnetAss** [comment]
I merged everything in the desktop github, I'm pretty sure it's all on the
same page and the pull request looks right.

**Comment by SpanishSurfer** [comment]
Merged, thanks!

**Comment by MagnetAss** [comment]
Was glad to get my feet wet in github with something simple :)

**Pull request merged**
